### PR TITLE
fix: verification url

### LINKED ISSUE #145: Issue: Invalid verification email
Verification email has localhost as its url
I'd love to fix this issue:

Screenshot 2023-10-02 at 3 54 33 PM

### PR DESCRIPTION
**Pull request by vatsalsinghkv**
fixes #145

### CODE REVIEW

File: backend/controllers/auth.controller.ts [hunk 1]
```diff
@@ -45,7 +45,7 @@ export const register = async (req: Request, res: Response) => {
       context: {
         subject: "Registration successfully",
         name: newUser.name,
-        link: `${BASE_URL}api/auth/verifyEmail/${emailVerificationToken}`,
+        link: `https://crm-webapp-zeta.vercel.app/api/auth/verifyEmail/${emailVerificationToken}`,
```
Comment (growupanand) [inline backend/controllers/auth.controller.ts:48]: Instead of using a hardcoded link, we can use environment variable so the link will not be dependent on a deployment. Currently we can use `FRONTEND_HOST`  environment variable which is defined in `backend/constants/index.ts`.

**Review by growupanand — CHANGES_REQUESTED** [review]
I have made some comments, can you please make changes accordingly?

File: backend/controllers/auth.controller.ts (hunk 1 above)
Comment (vatsalsinghkv) [reply backend/controllers/auth.controller.ts:48]: But There's not `FRONTEND_HOST` in `.env.example` file. So you'd need to add it in the env on hosting platform.

**Comment by vatsalsinghkv** [comment]
@growupanand I've updated the PR. And I've noticed there's a lot unused variables as imports which make code more messy, I'd recommend using eslint and prettier for taking care of things like removing unused variables & sorting imports etc

File: backend/controllers/auth.controller.ts (hunk 1 above)
Comment (growupanand) [reply backend/controllers/auth.controller.ts:48]: Great job on adding `FRONTEND_HOST` to the `.env.example` file! It's good practice to use this variable consistently throughout the codebase. Could you please update its usage here also?

**Additionally**, I noticed that in `.env.example`, the URL `https://crm-webapp-zeta.vercel.app/` is hardcoded. To make local development smoother, could you replace it with `http://localhost:3000`?

File: backend/controllers/user.controller.ts [hunk 2]
```diff
@@ -57,7 +57,7 @@ const resendEmailVerify = async (req: Request, res: Response) => {
     context: {
       subject: "Verification Mail",
       name: user.name,
-      link: `${BASE_URL}api/auth/verifyEmail/${newEmailVerificationToken}/`,
+      link: `${FRONTEND_HOST}api/auth/verifyEmail/${newEmailVerificationToken}/`,
```
Comment (growupanand) [inline backend/controllers/user.controller.ts:60]: As we are now using `FRONTEND_HOST` here, You can use `${FRONTEND_HOST}/auth/token/${newEmailVerificationToken}` route which you can see in `frontend/src/routes.tsx`.

**Note:** Currently that token page is used for two token types `"resetPasswordToken", "organizationInvitationToken"`, and we need to implement `newEmailVerificationToken` there in frontend which is seperate task.

**Review by growupanand — CHANGES_REQUESTED** [review]
Please review the comments where I've requested a few small final changes. Your attention to these adjustments is much appreciated. Thank you!

File: backend/controllers/user.controller.ts (hunk 2 above)
Comment (vatsalsinghkv) [reply backend/controllers/user.controller.ts:60]: Just checked the token page its amazing, and easy to organise ❤️

**Review by growupanand — APPROVED** [review]
